# アプリケーション名
spring.application.name=CampusTrade

# H2インメモリデータベースの設定
spring.datasource.url=jdbc:h2:mem:campustradedb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2管理画面(コンソール)の有効化 (http://localhost:8080/h2-console でアクセス可能)
spring.h2.console.enabled=true

# 起動時にEntityからテーブルを自動自動作成・更新する
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true